### ISSUE TITLE
Set JENKINS_HOME form pillar file

### ISSUE THREAD

**Issue by jkunjoonju18** [tcpcloud/salt-formula-jenkins#39]
Hi,

Is there a way to override the JENKINS_HOME value in this file: [jenkins](https://github.com/salt-formulas/salt-formula-jenkins/blob/master/jenkins/files/jenkins) from a pillar variable?

Thanks in advance for your help

**Comment by fpytloun** [comment]
Hello, it's not possible at the moment. But you can easily extend the file and map.jinja to add this option and submit pull request.

**Comment by jkunjoonju18** [comment]
OK will do thanks
