### ISSUE TITLE
Support for python3 / salt-300

### ISSUE THREAD

**Issue by lapfrank12** [tcpcloud/salt-formula-jenkins#44]
Hi Guys,

Do you have any plans to support Python3? The formula depends on `iteritems()` quite a bit, which is a python2 thing and is not supported in python3.

Related link here: https://github.com/saltstack/salt/issues/47461

Thanks,

Frank.

**Comment by fpytloun** [comment]
Hi, no plans but we always accept merge requests :-)

**Comment by BrianSidebotham** [comment]
You can close this issue off now with the merge of #45 :+1:

**Comment by fpytloun** [comment]
:+1:
